name: Generate GitHub Stats Cards

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Stats SVGs
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Stats Card
        uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.STATS_TOKEN }}

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "chore: update generated stats [skip ci]"
          git push
